#!/bin/bash

# (c) Harald Weidner, 2021-11-03
# License: MIT
#
# Checkmk local check
# Checks whether a system reboot is needed, e.g. after a kernel update.
# Currently, only Debian/Ubuntu and Red Hat and their derivates are supported.
#
# example output:
# 
# 0 Reboot_needed - No system reboot needed

CHECK=Reboot_needed
SEVERITY=2  # 1=WARN, 2=CRIT

[[ -f /etc/os-release ]] && source /etc/os-release

# Red Hat family
if type /usr/bin/needs-restarting >/dev/null 2>&1; then
  set -o pipefail
  version="x"
  if [ -f /etc/redhat-release ]; then
    version=$( cat /etc/redhat-release | grep -oP "[0-9]+" | head -1 )
  fi
  if [[ $version -eq "6" ]]; then
    reboot=$(/usr/bin/needs-restarting)
    ret=$?
    if [[ $ret -ne 0 ]]; then
      reboot="A system reboot is needed"
    else
      reboot="No system reboot needed"
    fi
  else
    reboot=$(/usr/bin/needs-restarting -r | tr '\n' ' ')
    ret=$?
    if [[ -z $reboot ]]; then
      reboot="(empty output of needs-restarting)"
    fi
  fi
  if [[ $ret -ne 0 ]]; then
    echo "$SEVERITY $CHECK - $reboot"
  else
    echo "0 $CHECK - $reboot"
  fi

# Debian / Ubuntu family
elif [[ $ID == "debian" || $ID_LIKE == "debian" || $ID == "ubuntu" || $ID_LIKE == "ubuntu" ]]; then
  if [[ -f /var/run/reboot-required ]]; then
    if [[ -f /var/run/reboot-required.pkgs ]]; then
      pkgs=$(cat /var/run/reboot-required.pkgs | tr '\n' ' ')
      echo "$SEVERITY $CHECK - A system reboot is needed due to updated packages: $pkgs"
    else
      echo "$SEVERITY $CHECK - A system reboot is needed"
    fi
  else
    echo "0 $CHECK - No system reboot needed"
  fi
fi
