#!/bin/bash
#
# (c) 2021 by Harald Weidner License: MIT
#
# Checkmk local check displays informations about pending yum (RPM) security updates
#
# place this in the checkmk agent "local/3600" directory (/usr/lib/check_mk_agent/local/3600 or similar) to cache results for an hour
#
# Runs "yum-check-update" to get all updates, then "yum updateinfo list updates sec" if any found The latter always returns zero on CentOS and some other distros
#
# Returns 2 (CRIT) if security updates pending (if OS reports these)
#         1 (WARN) if updates pending (may include security updates if non-rhel)
#         0 (OK) if no updates pending
#
# example output:
#
# 2 YUM_Updates updates=2 2 pending updates (1 security)

IFS=
if type yum >/dev/null 2>&1 ; then
  updatelist=$(yum check-update -q | egrep -v "Loaded plugins: langpacks, product-id, subscription-manager|^[ \t]|^$")
  seccount=0
  if [[ -z $updatelist ]] ; then
    updates=0
  else
    updates=$(wc -l <<< $updatelist)
  fi
  if [[ $updates -gt 0 ]] ; then
    seclist=$(yum updateinfo list updates sec -q | egrep -v "No update|^[ \t]|^$")
    if [[ -z $seclist ]] ; then
      result="1 YUM_Updates updates=$updates $updates pending updates"
    else
      seccount=$(wc -l <<< "$seclist")
      result="2 YUM_Updates updates=$updates $updates pending updates ($seccount security)"
    fi
  else
    result="0 YUM_Updates updates=0 No pending updates"
  fi
  IFS=$'\n'
  printf "$result\\\n"
  for line in $updatelist; do printf "$line\\\n"; done
  if [[ $seccount -gt 0 ]] ; then
    printf "\\\nSecurity Updates\\\n\\\n"
    for line in $seclist; do printf "$line\\\n\n"; done 
  fi
fi
